### ISSUE TITLE
Clicking links with dark theme [feature request]

### ISSUE THREAD

**Issue by Jdban** [talklittle/reddit-is-fun#106]
When I click a link (IE an imgur link), the loading screen his white, when blinds me during dark mode when browsing at night.

**Comment by adamweld** [comment]
Not sure what can be done about that, I'd be worried that if the background was made black, it would mess with some websites.

**Comment by talklittle** [comment]
I think it should be okay, the WebView background will cover the Activity background. I think this change makes sense especially for e.g. imgur links which have dark bg.

**Comment by talklittle** [comment]
I played around with it. Best I can do is have it use dark bg while loading, then change back to default white bg after page load finishes.

If I do not change back to white bg, it looks bad on some sites like amazon.com. Other sites like online.wsj.com are unaffected (because they explicitly define a white bgcolor maybe?).

On some sites w/ dark bg like imgur.com it is fine; the dark gray imgur bg will show up first, then the white bg will appear behind it. No longer blinds you!

On some sites, like gametrailers.com, it is bad because there will be a white flash before the bg shows up. Can't tell if it is because of a flaw in their site code, or just because of loading speed. Maybe has something to do with the redirection to m.gametrailers.com? I don't know.

Unfortunately this is probably the best I can do, without resorting to some weird hack detecting bgcolors in web pages.

**Comment by Jdban** [comment]
Awesome, that sounds perfect.
