### ISSUE TITLE
Not opening redd.it links in RiF anymore.

### ISSUE THREAD

**Issue by BrutalSauce** [talklittle/reddit-is-fun#175]
It used to be that when i clicked on a redd.it link it would open up in Reddit is Fun but it doesnt give me that option anymore.

**Comment by talklittle** [comment]
Thanks for the bug report. I'll look into the regression.

On Tue, Aug 16, 2011 at 3:16 PM, BrutalSauce
reply@reply.github.com
wrote:

**Comment by BrutalSauce** [comment]
Any new information on this?

**Comment by talklittle** [comment]
No, I haven't had time to look at it yet.

On Tue, Aug 23, 2011 at 10:21 AM, BrutalSauce
reply@reply.github.com
wrote:

**Comment by BrutalSauce** [comment]
Anyway i can get a previous version apk for this application so i can have the links open in reddit is fun?

**Comment by talklittle** [comment]
Sure thing -- if you head to https://github.com/talklittle/reddit-is-fun and
click the Downloads button, there is an archive of previous versions. Sorry
for the delay addressing the actual issue.
On Sep 6, 2011 12:45 PM, "BrutalSauce" <
reply@reply.github.com>
wrote:

**Comment by BrutalSauce** [comment]
So i figured out why its not opening the links anymore. Twitter recently changed all links to reroute through t.co. So the redd.it links arent really that anymore so the application doesnt see them. So im gonna go ahead and close this issue.

**Comment by talklittle** [comment]
Ah, I see. I appreciate you looking into it and detailing what the
cause was. Thanks!

On Thu, Sep 8, 2011 at 10:53 AM, BrutalSauce
reply@reply.github.com
wrote:

**Comment by stephenmcbride** [comment]
There is a page where developers can give feedback on the t.co shortener: https://dev.twitter.com/discussions/1360 . Like the reddit app, my own app used to open certain links when shortened by Twitter but no longer does because of the t.co change. It would be great if contributors here could add to the thread to make Twitter aware of the effect this change has had. I attempted to explain it to them but don't think I did a great job so please feel free to add :-) . Thanks.

**Comment by talklittle** [comment]
I just added a clarification to that thread that hopefully makes it
clear what the problem is.

On Fri, Sep 23, 2011 at 5:19 AM, Stephen McBride
reply@reply.github.com
wrote:
