### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#31]
as of version 0.8.6 the app is 500kb. I think lots of code can be refactored to reduce code size by almost 50%

**Comment by talklittle** [comment]
example: the AsyncTasks are huge and used in most of the Activities. they can probably be broken into 2 categories: GET and POST

**Comment by flowardnut** [comment]
I'll post a few comments on refactoring once I explore the code a little. You could've made the software a little more flexible by going with a 'reddit-is-fun' factory class that creates a reddit-is-fun app on the fly. </attempt at humor>

**Comment by kostmo** [comment]
regarding variable naming:
In my projects I've been naming all multi-part variables with the most generic part first, so that Eclipse groups them alphabetically by function (e.g. in the Package Explorer and in the auto-complete popup).  I see you're already doing this with the DIALOG_X constants.  You could also do it for names in strings.xml and for the names of layout files (e.g. list_item_comment.xml and list_item_inbox.xml).

My $.02

**Comment by digitalsurgeon** [comment]
also please seperate the reddit logic from the presentation, its quite hard to understand the code when the activities and http posting etc are all in the same file.

please create a lib just for communicating with reddit and the UI just uses that lib

**Comment by talklittle** [comment]
there is no reason to have this as an issue on the bug tracker so I'm closing it
