### ISSUE TITLE
API CHANGE: "invalid subreddit"

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#44]
getting "invalid subreddit" for some subreddits like /r/gaming and /r/funny, excluding frontpage and bestof.

I am pretty sure it's an API change with maybe the JSON object under "oembed" key.

Along with this there does seem to be some new cool info for threads which can be incorporated in the future.

**Comment by xenophile** [comment]
getting "invalid subreddit" on /r/all now which is pretty much all I use these days

**Comment by eligrey** [comment]
I think this is because KeyserSosa added an `is_self` property to self posts at my request. It's also likely that it could have to do with `oembed` or both.

talklittle: Please just do a normal loading bar (out of 100%) by using Content-Length to determine the total bytes loaded. Your current solution relies on a specific JSON structure, which is the wrong way to go about it, as JSON object properties are unordered and an application shouldn't fail whenever something is _added_. I think most users would be content with a normal loading bar, as they already know how may comments a post has, so they don't need to know how many are loaded unless you are displaying them live.

**Comment by talklittle** [comment]
eligrey: that is a very smart idea about the loading bar. I just need to figure out how to get the current byte using the JSON parser I'm using.

yes, my current solution does rely on specific JSON structure, and I know it's wrong, but didn't realize the impact when I first wrote it. therefore it is my priority to rewrite the parser.

And yes, it was the oembed that broke it (the nested JSON object specifically), not the is_self
