### ISSUE TITLE
Paid version does not log in to reddit correctly

### ISSUE THREAD

**Issue by ghost** [talklittle/reddit-is-fun#52]
When attempting to log in using the paid version, the "Logging in..." notification pops up and the application hangs there indefinitely.

This has happened every time I have tried to log in using the paid version.

Logging in still appears to work with the free version.

**Comment by talklittle** [comment]
Fixed

Strange bug caused by setting Constants.LOGGING to false (!), along with a too-short HttpPost params timeout of 30 seconds. (reddit.com is currently having a few server issues so the usually-instantaneous login takes some number of seconds instead)

Setting the timeout to 40s fixed for me. I'll set timeout to 45 seconds.
